name: Deploy React App

on:
  push:
    branches:
      - main  # Run this workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a Linux-based server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetch the latest code
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Using Node.js 18
          
      - name: Clean npm cache
        run: npm cache clean --force
        
      - name: Install Dependencies
        run: npm install  # Install all required dependencies

      - name: Build the Project
        run: npm run build  # Creates a production-ready build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the "gh-pages" branch
          folder: build  # Deploy the contents of the "build" folder
