name: Simple GitHub Actions Workflow

on: [push]  # Runs when code is pushed to the repository

jobs:
  run-basic-command:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetch the latest code

      - name: Print a Message
        run: echo "GitHub Actions is working!"  # Simple command
